# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HC0wwC5h3t6dPtgMGJ1ENWgJl7UIx6DR
"""

# =========================================================
# SECCIÓN: PASO 0 — OBTENCIÓN Y PREPARACIÓN DE DATOS (ENCAVI)
# Qué hace esta sección:
# 1) Busca el dataset ENCAVI 2023–2024 en datos.gob.cl (API CKAN)
# 2) Descarga la base en formato Stata (.dta)
# 3) Carga el archivo en pandas
# 4) Filtra jóvenes (18–29)
# 5) Conserva un set mínimo de variables y guarda un CSV listo para usar
# =========================================================

import os
import requests
import pandas as pd

CKAN = "https://datos.gob.cl/api/3/action"
QUERY = "Encuesta Nacional de Calidad de Vida y Salud (ENCAVI) 2023-2024"
FALLBACK_NAME = "encavi-2023-24"

os.makedirs("data", exist_ok=True)

def ckan(action, **params):
    r = requests.get(f"{CKAN}/{action}", params=params, timeout=90)
    r.raise_for_status()
    j = r.json()
    if not j.get("success"):
        raise RuntimeError(j)
    return j["result"]

# 1) Encontrar el dataset
res = ckan("package_search", q=QUERY, rows=1)
pkg = res["results"][0] if res.get("count", 0) > 0 else ckan("package_show", id=FALLBACK_NAME)

# 2) Elegir el recurso .dta
dta_url = None
for r in pkg.get("resources", []):
    if (r.get("format") or "").lower() == "dta":
        dta_url = r.get("url")
        break
if dta_url is None:
    raise RuntimeError("No encontré un recurso .dta en el dataset ENCAVI.")

# 3) Descargar
out_dta = "data/encavi.dta"
resp = requests.get(dta_url, stream=True, timeout=180)
resp.raise_for_status()
with open(out_dta, "wb") as f:
    for chunk in resp.iter_content(chunk_size=1024 * 1024):
        if chunk:
            f.write(chunk)

# 4) Cargar
df = pd.read_stata(out_dta)

# 5) Filtrar jóvenes 18–29
df_y = df[(df["edad"] >= 18) & (df["edad"] <= 29)].copy()

# 6) Variables mínimas
cols = [
    "folio_encuesta",
    "nom_region",
    "area",
    "sexo",
    "edad",
    "sum_comidas",
    "sum_comidas_cat",
    "valor_ipaq",
    "audit_cat",
]
cols = [c for c in cols if c in df_y.columns]
df_y_small = df_y[cols].copy()

# 7) Guardar CSV
out_csv = "data/encavi_jovenes_18_29.csv"
df_y_small.to_csv(out_csv, index=False)

print("OK — Paso 0 completado")
print("Archivo:", out_csv)
print("Dimensión:", df_y_small.shape)
df_y_small.head()

import pandas as pd

df = pd.read_csv("data/encavi_jovenes_18_29.csv")

# Para Paso 2 usamos solo filas sin NA en las dos variables
d = df.dropna(subset=["valor_ipaq", "sum_comidas_cat"]).copy()

A = d["valor_ipaq"].eq("Inactivo")
B = d["sum_comidas_cat"].eq("cuatro comidas")

n = len(d)
nA = int(A.sum())
nB = int(B.sum())
nAB = int((A & B).sum())

pA = nA / n
pB = nB / n
pAB = nAB / n
pAorB = pA + pB - pAB
pA_given_B = nAB / nB if nB > 0 else float("nan")
pB_given_A = nAB / nA if nA > 0 else float("nan")

print("n =", n)
print("nA =", nA, "  p(A) =", round(pA, 4))
print("nB =", nB, "  p(B) =", round(pB, 4))
print("nAB=", nAB,"  p(A∩B) =", round(pAB, 4))
print("p(A∪B) =", round(pAorB, 4))
print("p(A|B) =", round(pA_given_B, 4))
print("p(B|A) =", round(pB_given_A, 4))
print("p(Ac) =", round(1-pA, 4))
print("p(Bc) =", round(1-pB, 4))

# Paso 4–6 (mínimo): TLC con sum_comidas + IC (90/95/99) + Chi-cuadrado (IPAQ vs comidas)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

# --------------------
# Cargar datos (Paso 0)
# --------------------
df = pd.read_csv("data/encavi_jovenes_18_29.csv")

# -----------------------------------------
# PASO 4: TLC usando sum_comidas (bootstrap)
# -----------------------------------------
x = df["sum_comidas"].dropna().astype(float).values
B = 4000
ns = [30, 50, 100]

os_path = "data"
import os
os.makedirs(os_path, exist_ok=True)

tlc_summary = {}
for n in ns:
    means = np.array([np.mean(np.random.choice(x, size=n, replace=True)) for _ in range(B)])
    tlc_summary[n] = (means.mean(), means.std(ddof=1))

    plt.figure()
    plt.hist(means, bins=30)
    plt.title(f"Distribución muestral de la media (n={n})")
    plt.xlabel("Media muestral de sum_comidas")
    plt.ylabel("Frecuencia")
    plt.tight_layout()
    plt.savefig(f"data/tlc_media_sum_comidas_n{n}.png", dpi=200)
    plt.close()

# -----------------------------------------
# PASO 5: IC para la media de sum_comidas
# -----------------------------------------
n = len(x)
xbar = x.mean()
s = x.std(ddof=1)

def ci_mean_t(xbar, s, n, conf=0.95):
    alpha = 1 - conf
    tcrit = stats.t.ppf(1 - alpha/2, df=n-1)
    half = tcrit * s / np.sqrt(n)
    return (xbar - half, xbar + half, tcrit)

ci90 = ci_mean_t(xbar, s, n, 0.90)
ci95 = ci_mean_t(xbar, s, n, 0.95)
ci99 = ci_mean_t(xbar, s, n, 0.99)

# -----------------------------------------------------
# PASO 6: Test chi-cuadrado (valor_ipaq vs comidas_cat)
# -----------------------------------------------------
d = df.dropna(subset=["valor_ipaq", "sum_comidas_cat"]).copy()

tab = pd.crosstab(d["valor_ipaq"], d["sum_comidas_cat"])
chi2, pval, dof, expected = stats.chi2_contingency(tab)

# --------------------
# Resultados (para LaTeX)
# --------------------
out_lines = []
out_lines.append("=== PASO 4 (TLC) ===")
out_lines.append(f"sum_comidas: n_valid={n}, media={xbar:.4f}, sd={s:.4f}")
for nn in ns:
    m, sd = tlc_summary[nn]
    out_lines.append(f"TLC (n={nn}, B={B}): media_de_medias={m:.4f}, sd_de_medias={sd:.4f}  (grafico: data/tlc_media_sum_comidas_n{nn}.png)")

out_lines.append("\n=== PASO 5 (IC media sum_comidas) ===")
out_lines.append(f"n={n}, xbar={xbar:.4f}, s={s:.4f}")
out_lines.append(f"IC 90%: [{ci90[0]:.4f}, {ci90[1]:.4f}]  (t*={ci90[2]:.4f})")
out_lines.append(f"IC 95%: [{ci95[0]:.4f}, {ci95[1]:.4f}]  (t*={ci95[2]:.4f})")
out_lines.append(f"IC 99%: [{ci99[0]:.4f}, {ci99[1]:.4f}]  (t*={ci99[2]:.4f})")

out_lines.append("\n=== PASO 6 (Chi-cuadrado independencia) ===")
out_lines.append(f"n={len(d)} (sin NA en ambas variables)")
out_lines.append(f"chi2={chi2:.4f}, gl={dof}, p-valor={pval:.6f}")
out_lines.append("\nTabla de contingencia (primeras filas):")
out_lines.append(tab.head(10).to_string())

# guardar txt
with open("data/resultados_pasos_4_6.txt", "w", encoding="utf-8") as f:
    f.write("\n".join(out_lines))

print("\n".join(out_lines))
print("\nGuardado: data/resultados_pasos_4_6.txt")
print("Gráficos TLC guardados en: data/tlc_media_sum_comidas_n30.png, n50.png, n100.png")

from google.colab import files
import os

# Lista de archivos de gráficos a descargar
plot_files = [
    "data/tlc_media_sum_comidas_n30.png",
    "data/tlc_media_sum_comidas_n50.png",
    "data/tlc_media_sum_comidas_n100.png"
]

print("Descargando gráficos...")
for f_path in plot_files:
    if os.path.exists(f_path):
        files.download(f_path)
        print(f"  - {f_path} descargado.")
    else:
        print(f"  - ¡Error! El archivo {f_path} no se encontró.")
print("Descarga completada.")